// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Errors: typeof import('./src/components/errors.vue')['default']
    GeneralDataTable: typeof import('./src/components/generalDataTable.vue')['default']
    GeneralFormModal: typeof import('./src/components/generalFormModal.vue')['default']
    GeneralModal: typeof import('./src/components/generalModal.vue')['default']
    GeneralRender: typeof import('./src/components/generalRender.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingModal: typeof import('./src/components/settingModal.vue')['default']
    Sider: typeof import('./src/components/sider.vue')['default']
  }
}
