// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        Errors: typeof import('./src/components/errors.vue')['default']
        GeneralDataTable: typeof import('./src/components/generalDataTable.vue')['default']
        GeneralFormModal: typeof import('./src/components/generalFormModal.vue')['default']
        GeneralModal: typeof import('./src/components/generalModal.vue')['default']
        GeneralRender: typeof import('./src/components/generalRender.vue')['default']
        Header: typeof import('./src/components/header.vue')['default']
        NAvatar: typeof import('naive-ui')['NAvatar']
        NButton: typeof import('naive-ui')['NButton']
        NCard: typeof import('naive-ui')['NCard']
        NCheckbox: typeof import('naive-ui')['NCheckbox']
        NConfigProvider: typeof import('naive-ui')['NConfigProvider']
        NDataTable: typeof import('naive-ui')['NDataTable']
        NDrawer: typeof import('naive-ui')['NDrawer']
        NDropdown: typeof import('naive-ui')['NDropdown']
        NForm: typeof import('naive-ui')['NForm']
        NFormItem: typeof import('naive-ui')['NFormItem']
        NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
        NIcon: typeof import('naive-ui')['NIcon']
        NInput: typeof import('naive-ui')['NInput']
        NInputNumber: typeof import('naive-ui')['NInputNumber']
        NLayout: typeof import('naive-ui')['NLayout']
        NLayoutContent: typeof import('naive-ui')['NLayoutContent']
        NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
        NLayoutSider: typeof import('naive-ui')['NLayoutSider']
        NMenu: typeof import('naive-ui')['NMenu']
        NMessageProvider: typeof import('naive-ui')['NMessageProvider']
        NModal: typeof import('naive-ui')['NModal']
        NPagination: typeof import('naive-ui')['NPagination']
        NResult: typeof import('naive-ui')['NResult']
        NScrollbar: typeof import('naive-ui')['NScrollbar']
        NSpace: typeof import('naive-ui')['NSpace']
        NSpin: typeof import('naive-ui')['NSpin']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        SettingModal: typeof import('./src/components/settingModal.vue')['default']
        Sider: typeof import('./src/components/sider.vue')['default']
    }
}
